### ISSUE TITLE
[Request] Provide span in all instructions

### ISSUE THREAD

**Issue by VBGS** [HewlettPackard/dockerfile-parser-rs#16]
It seems to be impossible to get the span for the Run, Entrypoint and Cmd instructions that use the exec syntax.

**Comment by VBGS** [comment]
The fields of MiscInstruction being private, it is also impossible to access the span of Misc instructions.

**Comment by dsherret** [comment]
I also need this functionality. Opened https://github.com/HewlettPackard/dockerfile-parser-rs/pull/17
