### ISSUE TITLE
Parse failure on FROM with sha hashes

### ISSUE THREAD

**Issue by timothyb89** [HewlettPackard/dockerfile-parser-rs#7]
e.g.

```Dockerfile
FROM quay.io/pusher/wave@sha256:59246319ba2d49fe6096ca80627b02e91faba97a83d9f0231fb08238c315b5e2
```

...fails with:

```
[DEBUG] ignoring Dockerfile.test, could not parse as dockerfile: could not parse Dockerfile:  --> 3:25
  |
3 | FROM quay.io/pusher/wave@sha256:59246319ba2d49fe6096ca80627b02e91faba97a83d9f0231fb08238c315b5e2␊
  |                         ^---
  |
  = expected EOI
```

**Comment by dpc** [comment]
Is still a problem? In my use case we use these a lot so this failing would be a complete blocker.

**Comment by timothyb89** [comment]
Apologies for the slow response, however I've tentatively fixed this in https://github.com/HewlettPackard/dockerfile-parser-rs/pull/15. It may take a bit to merge and release since all the other reviewers are out for the holidays.
